### ISSUE TITLE
Error Saving Favicon

### ISSUE THREAD

**Issue by intrepidws** [studio1902/statamic-peak#102]
When I try to add an SVG, I get the following error:

```
ImagickException(code: 420): no decode delegate for this image format
```

Let me know if you need the entire stracktrace.

GitHub will not let me upload an SVG, but this is the code for the SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path d="M12 14l9-5-9-5-9 5 9 5z" />
  <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
</svg>
```

I have tried several different SVGs, all with the same result.

I am using Laravel Homestead, which has ImageMagick 6.9.7-4 installed.

**Comment by intrepidws** [comment]
It seems that adding this code to the top of the SVG code is necessary:

`<?xml version="1.0" encoding="utf-8"?>`

**Comment by robdekort** [comment]
Glad you found it! AFAIK you can only remove the SVG doctype when you're inlining SVG's in your templates. Otherwise you need it to prevent issues.

**Comment by intrepidws** [comment]
Thanks @robdekort - really enjoying Peak so far, well done.

**Comment by robdekort** [comment]
Really happy to hear that. Thanks.
