### ISSUE TITLE
Bug: prose-lg and larger aren't generating

### ISSUE THREAD

**Issue by that0n3guy** [studio1902/statamic-peak#110]
**Describe the bug**
I like to use typography's `prose` for my sites.  When messing w/ peak I couldn't get `prose-lg` to compile into site.css.

**To Reproduce**
Add `prose-lg` to a view, run `npm run dev`, then search through site.css.  You will find no `prose-lg`'s in there anywhere

**To fix**
To fix this I changed how typography is required in `tailwind.config.typography.js`

I did this:
```
  plugins: [
    require('@tailwindcss/typography'),

    // require('@tailwindcss/typography')({
    //   modifiers: [],
    // }),
  ]
```

I'm not sure why there is a blank `modifiers` on there anyways.   But this fixed my problem.

**Comment by robdekort** [comment]
Hey. Thanks. They're off on purpose since Peak uses fluid typography that scales from a small to large viewports. That's why there's usually no need for those modifiers. 

You can comment on a per project basis. That's why that's in the config.
