### ISSUE TITLE
bug: S3 config endpoint vs url 

### ISSUE THREAD

**Issue by that0n3guy** [studio1902/statamic-peak#111]
I spent hours trying to figure out why my S3 assets were working.  I finally figured out its because I was using endpoint instead of url in the confits.

Peak has the wrong variables set in the filesystems.php config file:

https://github.com/studio1902/statamic-peak/blob/7cb17412b18578222e2c0341d67c0122a2996498/config/filesystems.php#L64

It should be: 
`'url' => env('AWS_URL'),`

Here is what L8 has: 
https://github.com/laravel/laravel/blob/866589128430c55385cb13ddae0061c628245be2/config/filesystems.php#L51

**Comment by robdekort** [comment]
At 'some' point the config must've been correct. It's pretty hard to keep up with all config changes... I'd be happy to merge that in. I'm sorry it took you so much time.

**Comment by that0n3guy** [comment]
For sure, config changes are a pain sometimes.  I was working on it to late last night.  I noticed it right away this morning :).

**Comment by robdekort** [comment]
Classic!

**Comment by robdekort** [comment]
I'm on it and will update it right away btw.
