### ISSUE TITLE
tailwindcss class "text-right" not in site.css

### ISSUE THREAD

**Issue by scottgrayson** [studio1902/statamic-peak#113]
**Describe the bug**
tailwindcss class "text-right" not in site.css

**To Reproduce**
1. npm install && npm run dev
2. view public/css/site.css
3. search for text-right
4. See it does not exist

**Expected behavior**
I expected to have access to tailwind CSS classes. text-left and text-center do exist.

I tried this solution and saw no change. https://github.com/studio1902/statamic-peak/issues/110

**Comment by robdekort** [comment]
Peak uses the Tailwind JIT compiler which watches your templates for classes that you use and only compiles those. 

Make sure to read up on their docs to understand how it works. Use `npm run watch` to scan in your templates. 

Not a bug.

**Comment by vannut** [comment]
So that means that if your template(s) don't use `text-center` or `text-right` it won't make it to styles.css.
