### ISSUE TITLE
Split form fields from main form template

### ISSUE THREAD

**Issue by klickreflex** [studio1902/statamic-peak#116]
**Is your feature request related to a problem? Please describe.**
Currently there's a lot of placed in `form.antlers.html` that needs to be replicated when a certain from needs deviating styling. 

**Describe the solution you'd like**

I propose moving the fields, submit button and success message into a sub-partial called `form_fields.antlers.html` and referencing this in `form.antlers.html` (excerpt):

```html
        <div class="w-full">
            {{# Honeypot spam protection. #}}
            <div class="hidden">
                <label class="font-bold" for="{{ honeypot }}">{{ trans:strings.form_honeypot }} <sup class="text-yellow-400">*</sup></label>
                <input class="w-full form-input" id="{{ honeypot }}" type="text" name="{{ honeypot }}" tabindex="-1" autocomplete="off"/>
            </div>

            {{# render default-styled fields #}}
            {{ partial src="partials/form_fields" }}

        </div>
```

`form_fields.antlers.html` then contains the following:

```html
{{ fields }}
    <div class="flex flex-col space-y-4">
        <label class="font-bold" for="{{ handle }}">{{ trans key="{display}" }} {{ if validate | contains:required }}<sup class="text-yellow-400">*</sup>{{ /if }}</label>
        {{# Load notification when there is a validation error with the name field. #}}
        <template x-if="errors.{{ handle }}">
            {{ partial src="partials/notification" type="error" attribute="x-text='errors.{handle}'" }}
        </template>
        {{ field }}
    </div>
{{ /fields }}

{{# Pulse button and disable upon sending. #}}
<div class="flex justify-end md:col-span-12">
    {{ partial src="partials/button" as="button" label="{ trans:strings.form_send }" attribute='x-bind:disabled="sending" x-bind:class="&#123;&#39;opacity-25 cursor-default&#39;: sending&#125;"' }}
</div>
<template x-if="success">
    {{ partial src="partials/notification" type="success" class="md:col-span-12" content="{trans:strings.form_success}" }}
</template>

```

This allows to create different styled partials for certain forms while keeping the main work load in a central place.

**Describe alternatives you've considered**
– 

**Additional context**
I've got a form that needs to be special treatment, but should use the same AJAX logic which I didn't want to duplicate, so I move stuff into partials and loaded the correct fields partial depending on the form handle:
![image](https://user-images.githubusercontent.com/435825/125761715-b5571fa8-7ad9-479c-9838-5d8a8744fd58.png)

**Comment by robdekort** [comment]
I like this and will try to get it in https://github.com/studio1902/statamic-peak/pull/114. Thanks!

**Comment by robdekort** [comment]
Done! Should it what folder should the partial live do you think? Components or snippets?
