### ISSUE TITLE
Could not authenticate against github.com

### ISSUE THREAD

**Issue by tusamni** [studio1902/statamic-peak#124]
**Describe the bug**
When creating a new Statamic project and using the Peak starter kit, it errors out with the following:

`In AuthHelper.php line 113: Could not authenticate against github.com

**To Reproduce**
1. In VSCode termnial: "statamic new statamic studio1902/statamic-peak"
2. Statamic installs fine
3. During "Preparing starter kit" error appears

**Expected behavior**
Install Peak as expected.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/9271145/132239324-23206b8f-3537-443f-b17c-bbda69734e49.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Beta Channel
 - Browser: Chrome
 - Version: Version 93.0.4577.63 (Official Build) (64-bit)

**Additional context**

**Comment by robdekort** [comment]
Hey there. This has nothing to do with Peak I'm afraid but with the way the starter kits/cli works. Did you try and add your public key to GH?
