### ISSUE TITLE
Clarification what is "peak" and what is "Statamic" from the page builder

### ISSUE THREAD

**Issue by torian257x** [studio1902/statamic-peak#125]
hi
I'm new to peak / statamic. That means I have no good understanding of statamic.

Your package got recommended, I tried it out and I like it.

What I don't understand at all is what part is peak and what is statamic. If I work without peak, what do I not have?

afaik statamic has a page builder as well called bard, that you use. Can you clarify what part of your page builder is different if something is different at all?

**Comment by robdekort** [comment]
Please don't use issues for this. This is intended for bug tracking. Please read the Statamic and Peak docs and if you then still have questions try Discord.

**Comment by torian257x** [comment]
yes, this is my issue with the documentation.

But thanks, I'll try discord next and see if someone is able to answer that there.
