### ISSUE TITLE
Call to a member function get() on null in GenerateSocialImages.php:16

### ISSUE THREAD

**Issue by torian257x** [studio1902/statamic-peak#129]
**Describe the bug**
I'm pretty sure I'm lacking something that you guys expect that I have and I don't.

When accessing the cp dashboard  I get an error in the logs and some part of the dashboard doesnt load
error looks like so
![image](https://user-images.githubusercontent.com/2072058/134451971-866ceb66-30c2-443b-b285-884d60817dfb.png)

`->inDefaultSite()` returns null

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser chrome
 - Version 82

**Additional context**
I installed it into my existing statamic installation
```
$ composer show statamic/cms
name     : statamic/cms
descrip. : The Statamic CMS Core Package
keywords : cms, flat file, laravel, statamic
versions : * v3.2.6
```

**Comment by torian257x** [comment]
argh...
i had to copy the new  globals into the multi site folders

looks like so
![image](https://user-images.githubusercontent.com/2072058/134453662-84bce2a0-7ca2-425b-badf-81198bd34e04.png)

**Comment by robdekort** [comment]
Happy you solved it.

**Comment by jmartsch** [comment]
I experience the same error when running `php please peak:clear-site` after a fresh install.
Running `php please cache:clear` first, and then the `php please peak:clear-site` command solved it for me.

**Comment by robdekort** [comment]
Running which version @jmartsch?

**Comment by marcorieser** [comment]
Tried it successfully with a fresh site `statamic new my-project studio1902/statamic-peak` and `php please peak:clear-site`. Added a check to prevent such errors half a month ago (https://github.com/studio1902/statamic-peak-seo/pull/5).
