### ISSUE TITLE
Always render indexing fields

### ISSUE THREAD

**Issue by aerni** [studio1902/statamic-peak#132]
I just leave you with this thought I had:

`noindex` and `nofollow` should probably always render and not just on `production`. A common use case is to set those two values when testing your site on a staging server that has an environment of `staging`. As of now, the tags wouldn't render in that environment.

https://github.com/studio1902/statamic-peak/blob/16494c947fd25b9ed922412277c99405b725559b/resources/views/snippets/_seo.antlers.html#L29-L40

**Comment by aerni** [comment]
Hahaha sorry, never mind. You've got an `else` in there that automatically sets `noindex, nofollow`.

But maybe still a good idea to give the user that level of control no matter the environment.

**Comment by robdekort** [comment]
Thanks! I usually just set my env to `production` when I want to test the trackers on `local` :-).

But we could make it configurable for sure. A toggle? Something like `Render on all environments`?
