### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by jdivins** [studio1902/statamic-peak#135]
## Describe the bug
@robdekort I think that in this documentation page anchor: 
https://peak.studio1902.nl/features/assets.html#background-images
Html example **_selector_** must be **_class_** or change **_selector_** to **_class_** in file:
https://github.com/studio1902/statamic-peak/blob/main/resources/views/snippets/_background_image.antlers.html

**Comment by robdekort** [comment]
Thank you!
