### ISSUE TITLE
Noscript tag with parapgraph in head of document

### ISSUE THREAD

**Issue by vannut** [studio1902/statamic-peak#143]
In [_noscript.antlers.htm](https://github.com/studio1902/statamic-peak/blob/main/resources/views/snippets/_noscript.antlers.html)l there is a paragraph injected when the browser isn't using javascript. 

But this `<noscript>` block is referenced in [the head of the document.](https://github.com/studio1902/statamic-peak/blob/main/resources/views/layout.antlers.html#L14) 
So the paragraph also gets displayed in the `<head>`

That doesn't seem right, right?

**Comment by robdekort** [comment]
Totally works though...
