### ISSUE TITLE
404 on packagist

### ISSUE THREAD

**Issue by odeke** [studio1902/statamic-peak#147]
![image](https://user-images.githubusercontent.com/1935464/138216856-d44c0373-179f-4508-9c61-2edc5d14fd8e.png)

Visit https://repo.packagist.org/p2/studio1902/statamic-peak.json
which is used when installing the package.

**Comment by odeke** [comment]
Here's the attempt for peak.
![image](https://user-images.githubusercontent.com/1935464/138237920-532dea11-e147-4bdd-8f62-7169749190e0.png)

**Comment by robdekort** [comment]
Lot's of different errors can occur when you're not authenticated as the CLI can't auth. with GH. Hope this helps / solves your issue.

**Comment by odeke** [comment]
FYI, your support level: Godlike 🤩
