### ISSUE TITLE
Efficiency suggestions

### ISSUE THREAD

**Issue by jasonvarga** [studio1902/statamic-peak#158]
This isn't a bug, but just some suggestions for improvements.

In certain views, there is more work being performed than there needs to be.

Here's a few examples.

### Asset tag in picture component

https://github.com/studio1902/statamic-peak/blob/dffb99fddf748ad4dcd6463375c229788139cf6d/resources/views/components/_picture.antlers.html#L8

The `asset` tag is not needed here. It's only needed if `image` is a string.
I could be wrong, but I believe `image` is always going to be an `Asset` instance since it's coming from an `assets` fieldtype. (Through the `figure` partial).

https://github.com/studio1902/statamic-peak/blob/dffb99fddf748ad4dcd6463375c229788139cf6d/resources/views/components/_figure.antlers.html#L17-L18

You can replace `{{ asset :url="image" }} ... {{ /asset }}` with `{{ image }} ... {{ /image }}`.

---

### Glide tags use URLs instead of Assets

There are a number of places where `glide` tags are getting URLs passed into them.

https://github.com/studio1902/statamic-peak/blob/dffb99fddf748ad4dcd6463375c229788139cf6d/resources/views/components/_picture.antlers.html#L14

https://github.com/studio1902/statamic-peak/blob/f265f14be462050178d397d212ec184e657237e3/resources/views/snippets/_background_image.antlers.html#L7

https://github.com/studio1902/statamic-peak/blob/f265f14be462050178d397d212ec184e657237e3/resources/views/snippets/_background_image.antlers.html#L15

In most cases you already have the asset instance. You can just pass that directly into it.

Replace with `{{ glide:image }}`, `{{ glide :src="image" }}`, and `{{ glide:image }}` in the above snippets respectively.

(There won't be any improvement until https://github.com/statamic/cms/pull/4585 is released, though.)

---

### Converting to string

This isn't really happening in Peak where it's a problem, but something to keep in mind is turning things into strings in parameters unnecessarily.

https://github.com/studio1902/statamic-peak/blob/dffb99fddf748ad4dcd6463375c229788139cf6d/resources/views/snippets/_background_image.antlers.html#L7

This would be better as `:src="image"`.

https://github.com/studio1902/statamic-peak/blob/dffb99fddf748ad4dcd6463375c229788139cf6d/resources/views/email/form_owner_text.antlers.html#L11

Instead, do: `{{ trans :key="display" :locale="locale" }}`
Again, not an issue here because they're strings anyway.

The main place this would be an issue (I've seen it on Peak sites in the wild) is when using the picture component.

https://github.com/studio1902/statamic-peak/blob/dffb99fddf748ad4dcd6463375c229788139cf6d/resources/views/components/_figure.antlers.html#L17-L18

If you were to do `image="{image}"`, you'd end up converting the `image` (an Asset) to a URL string, pass it into the partial, where URL would be used to look up an Asset.

**Comment by sjclark** [comment]
Is there any place where all the above suggestions are documented? Some sort of General Statamic Performance Pointers page? All seems like super good ideas, but I never would’ve thought of half of these without them being pointed out tbh 🤷‍♂️
