### ISSUE TITLE
Customization - how to do it conveniently?

### ISSUE THREAD

**Issue by vladdu** [studio1902/statamic-peak#16]
Unless I'm missing some obvious way, I'm not sure how to handle customization. I mean, I have a few different opinions about how I want some details laid up, and I can have those in a separate private branch, but it might not be an easy task to keep it rebased, as the configuration is not always cleanly separated.

Do you have any suggestions about how that could be handled?

I suppose that the tailwind configuration is what's mostly at stake. One starting point could be to extract the css configuration from tailwind.config into files that get imported.

For my own templates, partials, blue and fieldsets, I can use an add-on (I think). Maybe it would be useful to provide one, so that people can just provide the content? Maybe not everyone can code.

**Comment by robdekort** [comment]
Not really. I'm not even sure if I will update my own sites to keep up with the latest Peak additions. It would probably change a lot on a project basis anyway. I'd use it more like a starting point and merge new additions in the other way around.

But I'm very curious about your opinions. Maybe it's good to discuss some to see if it would make sense to merge it in?

**Comment by vladdu** [comment]
Maybe this is more of a problem while Peak is actively developed while my site is not published yet, so there's always the wish to get the freshest tools. Also it feels nice to go to any of my sites and not have to remember what the configuration was, it takes a while for me to realize "oh, here I didn't have this thingie, that's why it's not working!"

I think the tailwind config is mostly affected. There are many different plugins, some with a lot of configuration. For example, I would like to have the css config you are adding to tailwind as a separate file, as well as the @tailwindcss/typography config.

The rest is probably just things I prefer (like always install statamic/ssg and @tailwindcss/ui). If there's something I feel is more generic I will submit a PR.

**Comment by robdekort** [comment]
Yeah, I get what you're saying. About the TW file: I've thought about separating it, but t.b.h. I think it's actually really convenient to have it just one file. When separating it, you have to make choices for what to separate and what not. Maybe this is something to revisit. Please share if you have a nice way of doing this. I'm very much open to change!

**Comment by robdekort** [comment]
Closing this for now! Please feel free to add issues for individual stuff that should be up for debate!

**Comment by vladdu** [comment]
ok
