### ISSUE TITLE
View Front Matter value not being selected in Bard block

### ISSUE THREAD

**Issue by PunchRockgroin** [studio1902/statamic-peak#164]
**Describe the bug**
The 'sizes' view front matter array key not being selected when the front matter view array key is called from a Bard block. It's a bit confusing to describe, but, for example, when using the "figure" block in the Bard field set "Figure", the sizes array value is not passed along to the partial:components/picture, resulting in a empty sizes attribute

**To Reproduce**
1. Fresh install of Statamic Peak
2. Visit long form content under 'examples'
3. Scroll down to the mountain peak image
4. In dev tools, view the HTML source and the source tag sizes attribute is empty

**Expected behavior**
The size attribute there should be the value of the 'xl' key, which is '90vw' as outlined in  resources/views/components/_figure.antlers.html

**Screenshots**
![image](https://user-images.githubusercontent.com/1855836/139499045-73f1f926-423b-4c82-a6b0-b73caeb6d88f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Laravel Homestead 
 - Browser: All

**Additional context**

Introduced in https://github.com/studio1902/statamic-peak/pull/137

The view front matter value is called correctly when you use the figure partial directly and set the "size" value explicitly, as is used with the "notification" partial in the forms.  However, as a Bard block, it does not work. I noticed this because I tried creating a new Bard block and using the same front matter style as the "figure" template, and could not get my front matter values to show, but when using the partial directly in a template and setting the attribute value the front matter array key/value is chosen correctly.

**Comment by robdekort** [comment]
Great find. Thank you.
