### ISSUE TITLE
Add Email, to the Social Media Block

### ISSUE THREAD

**Issue by edalzell** [studio1902/statamic-peak#167]
**Is your feature request related to a problem? Please describe.**

Quite often in the footer, one has an email link along w/ the social media links. Would be nice to have them all defined in the same spot.

**Describe the solution you'd like**

Add `Email` as a replicator set to the `social media` blueprint.

**Describe alternatives you've considered**

A global.

**Comment by robdekort** [comment]
Hey thanks. Do you mean to have one in the bottom right corner together with an envelope icon, together with the social media accounts? I think that's fair!

I often have contact info in the footer on my sites. It usually includes an address and phone numbers as well. Most of the time I add it to the configuration global but I don't think it hurts having another option in the social media global.
