### ISSUE TITLE
Social Media URL field is not URL

### ISSUE THREAD

**Issue by edalzell** [studio1902/statamic-peak#168]
**Describe the bug**

Right now the Social media field is `URL` but because of the default prefixes it's not really an URL you enter, it's a 'handle'.

Perhaps the name could be changed?

**To Reproduce**
1. Go to Social Media global
2. Add Twitter block
3. Use your eyes to see the text 'URL'

**Expected behavior**

Should be `Handle`

**Comment by robdekort** [comment]
But now I have to add e-mail (#167). How should I name it? And e-mail is not social media. ;-)

**Comment by robdekort** [comment]
Ah you meant the visual label. Gotcha.
