### ISSUE TITLE
Suggestion - Comments for each component/partial

### ISSUE THREAD

**Issue by edalzell** [studio1902/statamic-peak#180]
One of the hardest things to do, when taking over a site, is to figure out where to make changes. I often open up the dev tools, find the bit I'm interested in then do searches to try to find it.

In the starter kit I use, for my day job, we have HTML comments in each component:
```html
<!-- Component Foo -->
...
<!-- End Component Foo -->
```

This makes it super easy to quickly find the right partial to edit.

I'm happy to PR this, if you feel this would benefit others.

**Comment by robdekort** [comment]
I see that makes sense. I wouldn't use it myself but maybe others. Happy to merge it in.

**Comment by robdekort** [comment]
Since you came up with this idea I needed it like 10 times on older sites. Did you start this already or do you want me to take it up?

**Comment by edalzell** [comment]
Haven't started yet

**Comment by robdekort** [comment]
So happy you started using Peak...
