### ISSUE TITLE
Hreflang tags broken

### ISSUE THREAD

**Issue by Adrianjs42** [studio1902/statamic-peak#181]
**Describe the bug**
it seems that if you have created a multisite, the sitemap generator only creates the default locale

**To Reproduce**
1. Install statamic peak example
2. run `php please multisite`, see eg. https://statamic.dev/multi-site 
3. Create another page for the new locale
4. go to /sitemap.xml and see the xml for only one locale

**Expected behavior**
The sitemap.xml should generate the sitemap.xml for both locales, eg. 'en' and 'fr'

In the best case we could add a sitemap with hreflang, see example here: https://developers.google.com/search/docs/advanced/crawling/localized-versions#example_2 

**Screenshots**

**Additional context**
seems like we need to adjust the sitemap.antlers file at /resources/views/sitemap/sitemap.antlers.xml

**Comment by robdekort** [comment]
Hi Adrian! Thanks for your report.

I'm aware of this however I never implemented this because:

- Each entry has automatic `hreflang` tags (when you turn this on) so Google will crawl
- Sitemaps are becoming less important as search engines are becoming smarter. 

However if you think this is essential we should look into it. What do you think?

**Comment by Adrianjs42** [comment]
@robdekort nice to know! For me it's then only a 'nice to have feature'.
I saw that after my latest statamic-peak update, the hreflang is not set correctly.

When i comment the following code snippet in resources/views/snippets/_seo.antlers.html         
```
{{#  Quickfix comment - after peak update not working
    {{ seo:hreflang_sites where="{locale:handle}" limit="1" }}
        <link rel="alternate" hreflang="{{ locale:full replace="_|-" }}" href="{{ permalink }}">
    {{ /seo:hreflang_sites }}
#}}
```
and I replace this by:
`<link rel="alternate" hreflang="{{ locale:full replace="_|-" }}" href="{{ permalink }}">`

Then it's working again

**Comment by robdekort** [comment]
Darn, this wasn't broken at some point. We need to check the global array though so that fix is is a little too simplistic.

**Comment by robdekort** [comment]
Simplified the configuration. It's now working correctly. Thank you.
