### ISSUE TITLE
Suggestion - Routes/CSRF

### ISSUE THREAD

**Issue by edalzell** [studio1902/statamic-peak#186]
Please note these are only suggestions, everything works fine.

First, you don't need the code in the `VerifyCsrfToken` middleware, that's only used for `POST` requests, and your code does a `GET`.

Second, if you made the GenerateToken controller into an addon, you could auto generate the route so you don't have to add it manually to the `web.php`. You wouldn't have to publish the addon anywhere, just have it in the `addons` folder. Keeps things a bit tidier.

**Comment by robdekort** [comment]
Interesting thanks. I'm probably not gonna turn it into an addon right now but redundant code is a waste. Thanks, making note of this.
