### ISSUE TITLE
An asset container has not been configured

### ISSUE THREAD

**Issue by thetemplateblog** [studio1902/statamic-peak#205]
**Describe the bug**
This is a fresh install deployed with forge. I can't create a page

**To Reproduce**
1. Go to 'cp | Collections | Pages'
2. Click on 'Create Entry'
3. See error

**Expected behavior**
Create a new Page

**Error**
Statamic\Fieldtypes\Assets\UndefinedContainerException
An asset container has not been configured
https://dietpinch.com/cp/collections/pages/entries/create/default
[Hide solutions]()
Assets fieldtype is missing the "container" option.
Since you have multiple asset containers, you need to specify which one should be used in the field.

**Additional context**

**Comment by robdekort** [comment]
Hey, this is not something I can recreate. The default page blueprint  doesn't use an asset field and the image field in the common fieldset has a container specified.

I'm not sure if this is a Peak thing. Are you using an asset field in this install?

**Comment by thetemplateblog** [comment]
Weird, I reinstalled it and it works fine. Thanks for checking!

**Comment by robdekort** [comment]
Good to hear!
