### ISSUE TITLE
Change cookie banner default text

### ISSUE THREAD

**Issue by kamilms21** [studio1902/statamic-peak#215]
It's absolutely terrible idea to commit text messages like this "'Third party cookies absolutely terrible for privacy, but we don\'t give a sh*t.", especially this theme is available in Statamic market. Consider changing this for something less harmful

**Comment by robdekort** [comment]
Not this way buddy.

**Comment by jonassiewertsen** [comment]
@robdekort I love the default text a lot 🤘

Those who need a different text can easily change it right here:
https://github.com/studio1902/statamic-peak/blob/main/lang/en/strings.php#L24
