### ISSUE TITLE
article from _prose.antlers.html overwrites button tag

### ISSUE THREAD

**Issue by Sukrams** [studio1902/statamic-peak#237]
**Describe the bug**
In Statamic 3.3.25 the components/_button.antlers.html inherits the `article` atribute for the HTML tag from the typography/_prose.antlers.html.

So the tag for the button will be `<article>` instead of `<a>` and so the styling is missing.

**To Reproduce**
1. Update to statamic 3.3.25
2. Use a button in a n article-set 
3. See the button will get an `<article>` instead of `<a>` and the styling is missing

**Expected behavior**
Until Statamic 3.3.24 the button got it's correct class and styling

**Screenshots**
![Bildschirmfoto 2022-08-03 um 01 52 14](https://user-images.githubusercontent.com/15678176/182495865-2886c5f0-bac9-42d2-8e59-a8cb66126b50.png)

**Additional context**
With statamic 3.3.24 everything is fine, with 3.3.25 it's broken.

**Comment by robdekort** [comment]
That looks very odd. I’d have to try and reproduce and maybe report a bug at the Statamic repo. Currently on vacation. Will try to look into it soon.

**Comment by Sukrams** [comment]
@robdekort is it maybe causing by this PR? https://github.com/statamic/cms/pull/6405

If I add `as="a"` to the include for the `button.antlers.html` in the buttons component it works, so it seems like it's inhereting the `article` parameter from the prose component.

Have a nice vacation!

**Comment by robdekort** [comment]
Yeah that could very well be it. I'll reach out to John because this will break a lot of sites I'm afraid.

**Comment by robdekort** [comment]
Yeah this change in Statamic is indeed breaking. I added a comment to that PR.

**Comment by robdekort** [comment]
I'll add the `as="a"` to the buttons partial in Peak for now to make sure new users don't run into this. Maybe the PR will be reverted so active installs don't break.

**Comment by robdekort** [comment]
The PR for `statamic/cms` will be reversed in the next update. Thanks for reporting this.

**Comment by robdekort** [comment]
Update is live!
