### ISSUE TITLE
Vite and compiling cp.js

### ISSUE THREAD

**Issue by freshface** [studio1902/statamic-peak#242]
**Describe the bug**
I want to compile cp.js and load it into the control panel

**To Reproduce**

I added cp.js to the vite.config.js file

```
import laravel from 'laravel-vite-plugin'
import { defineConfig, loadEnv } from 'vite'

export default defineConfig(({ command, mode }) => {
    const env = loadEnv(mode, process.cwd(), '')
    return {
        plugins: [
            laravel([
                'resources/css/site.css',
                'resources/js/site.js',
                'resources/js/cp.js',
            ])
        ],
        server: {
            open: env.APP_URL
        }
    }
});

```

I also activated   `Statamic::script('app', 'cp'); `in AppServiceProvider.php 

**Expected behavior**
The control panel to load my custom javascript.
But the control panel tries to load the following path: http://127.0.0.1:8000/vendor/app/js/cp.js?v=spQH8j3Iy5ntP1Lh

I dont think the cp and vite compiler play nice.
Vite compiles to public/build instead of vendor/app

**Comment by robdekort** [comment]
Not really sure what I can do about this.
