### ISSUE TITLE
custom fonts fail in build or watch process

### ISSUE THREAD

**Issue by delz-dev** [studio1902/statamic-peak#244]
done like in the docs:
https://peak.1902.studio/other/custom-fonts.html#convert-your-font-files

but:
<img width="1057" alt="CleanShot 2022-08-22 at 15 59 11@2x" src="https://user-images.githubusercontent.com/54885840/185939269-e5843f78-196b-4c33-8be1-9900b8748696.png">

there's something wrong in the vite.config.js but don't have a solution :-p

**Comment by robdekort** [comment]
<img width="680" alt="Screenshot 2022-08-22 at 16 03 12" src="https://user-images.githubusercontent.com/69107412/185940246-73a01610-560c-49ff-8cc6-5008efde5193.png">
Try this. It's required for Vite. I'll update the docs. Thanks!

**Comment by delz-dev** [comment]
no – doesn't work 
<img width="973" alt="CleanShot 2022-08-22 at 16 08 56@2x" src="https://user-images.githubusercontent.com/54885840/185941595-d8d6bc2a-07ea-4e54-91da-e2db78635291.png">

<img width="861" alt="CleanShot 2022-08-22 at 16 09 12@2x" src="https://user-images.githubusercontent.com/54885840/185941630-fc49942d-954d-4973-850e-f02bf47b7317.png">

**Comment by robdekort** [comment]
It should. Does here. Did you restart vite by hitting `ctrl+c` and then `npm run dev`? Is your App URL in your `.env` correct? Can you confirm Vite copied the font files to `public/build/assets`?

**Comment by robdekort** [comment]
Hey your previous comment is gone. Did you fix this Patrick?

**Comment by rhettparkinson** [comment]
Hi Rob! I'm actually running into a similar issue. Any help you might offer would be appreciated :D

I've used the example you provided in the docs for loading static font files (https://peak.1902.studio/other/custom-fonts.html#include-your-fonts), and Vite resolves the correct url, (eg. http://127.0.0.1:5173/public/fonts/Figtree-Regular.woff2), and I can see the compiled 'site.css' is correctly referening the font-family. 

I'm wondering if this is maybe a Vite issue? I'm using Docker and Laraval Sail, for what it's worth.

**Comment by rhettparkinson** [comment]
Nevermind, turns out the issue was with the WOFF2 files themselves (they were WOFF files downloaded directly from Google Fonts). I swapped out for another set of WOFF files and it worked as it should 👍 cheers

**Comment by robdekort** [comment]
Glad you figured it out!
