### ISSUE TITLE
i was trying to run this repo but it does not working, now i can not run any laravel app, how to fix this?

### ISSUE THREAD

**Issue by tanveerulhassan** [studio1902/statamic-peak#295]
![image](https://user-images.githubusercontent.com/53822107/211158337-265015b3-9c33-4371-9c15-54f4905de282.png)
I was trying to run this repo but it does not work, now I can not run any laravel app, how to fix this? using laragon

![image](https://user-images.githubusercontent.com/53822107/211158361-63953f0c-710d-40df-b326-020f6a22b86d.png)

**Comment by robdekort** [comment]
That error seems pretty self explanatory and has nothing to do with Peak.

**Comment by tanveerulhassan** [comment]
I can understand. But everything was working fine before. As I tried to
clone this project this error came. Now I can't run any new Laravel app
even uninstalled Laragon Composer many times but same issue after each
update

**Comment by vannut** [comment]
It looks like you added an github oauth token to your install. 

But that token is invalid, as it has " and [] in it. Try to install a good oauth token and everything will be fine.
