### ISSUE TITLE
Add support for Dark Mode

### ISSUE THREAD

**Issue by rabiibrahimi** [studio1902/statamic-peak#297]
**Is your feature request related to a problem? Please describe.**
Documentation says that there is no support for dark mode but it doesn't work, followed documentation (there is no darkMode: 'class') under tailwind.config.js and also there is no component by name {{ partial:components/theme_toggle }}.

**Describe the solution you'd like**
Just add those missing vaiables, add darkMode in tailwind.config.js and add component. 
 
**Describe alternatives you've considered**

**Additional context**

**Comment by robdekort** [comment]
Hey Rabii. This recently changed. You have to install the files first using `php please peak:install-preset`. I'll update the docs. Thanks.
