### ISSUE TITLE
Can we allow the stubs to be published so it's possible to override them?

### ISSUE THREAD

**Issue by RiaanZA** [studio1902/statamic-peak#299]
**Is your feature request related to a problem? Please describe.**
The default "add block" template stub contains css classes that don't fit in with my theme. It will speed up my dev process if I can edit the stub to use classes matching my layout instead of having the need to edit them every time I create a new block

**Describe the solution you'd like**
Add the ability to vendor:publish the stubs so that users can over ride them if needed

**Comment by robdekort** [comment]
Closing because this is a FR. Please open up a discussion and / or PR.

**Comment by robdekort** [comment]
Also this belongs on the `statamic-peak-commands` repo.
