### ISSUE TITLE
Fluid font-size

### ISSUE THREAD

**Issue by willemvb** [studio1902/statamic-peak#30]
Hey guys,

I love your super handy theme. Small question about the fluid typography configuration:

Shouldn't these values be the same?

https://github.com/studio1902/statamic-peak/blob/main/tailwind.config.js#L278
https://github.com/studio1902/statamic-peak/blob/main/tailwind.config.js#L295

Thanks!
Willem

**Comment by robdekort** [comment]
Hi Willem. Thanks, that's good to hear. You're absolutely right. I moved it to root but I didn't remove it from html and I think we could just remove that. 

I'll test and update later. Thanks!

**Comment by robdekort** [comment]
Fixed this. Thanks.
