### ISSUE TITLE
Dashboard collection error: Call to a member function whereAnyStatus() on null

### ISSUE THREAD

**Issue by MartijnThomas** [studio1902/statamic-peak#309]
**Describe the bug**
After a clean install of Statamic and Peak, I get an error on the dashboard page `Call to a member function whereAnyStatus() on null`. I traced it down to the pages collection widget in `config/cp.php`. The list of pages is also missing on the dashboard. It is not limited to the pages collection, any collection will have this issue.

_Edit 1_: A clean install of Statamic without Peak, and a collection widget added to the Control Panel, did not result in this error.

**To Reproduce**
1. Run `statamic new my-site studio1902/statamic-peak`
2. Go for all the default options in console and create a super user
3. Login to the control panel

**Expected behavior**
A list of pages on the dashboard homepage and no error.

**Screenshots**
<img width="1287" alt="Dashboard collection error" src="https://user-images.githubusercontent.com/3611378/226261312-4e76f6f6-e300-42cb-95f3-b514061b35e7.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1 & Laravel Valet
 - Browser: Safari & Chrome
 - Version: Statamic 3.4.6. & Peak 11.5

**Comment by robdekort** [comment]
This seems to be a bug in core: https://github.com/statamic/cms/issues/7724 Keep an eye out on that one.

**Comment by robdekort** [comment]
This should be fixed in the just tagged Statamic release: https://github.com/statamic/cms/releases/tag/v3.4.7
