### ISSUE TITLE
statamic 4.0: '+' button stays over typed text

### ISSUE THREAD

**Issue by ymarkus** [studio1902/statamic-peak#316]
**Describe the bug**
When I type in the article field, the plus button always stays over the text I'm currently typing

**To Reproduce**
1. Install statamic version 4
2. Try typing in an 'article' field

**Screenshots**
![2023-05-10T10-09-02](https://github.com/studio1902/statamic-peak/assets/62380378/4369b54a-cafe-46d7-a176-940158583e0a)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser Mozilla Firefox 112.0.2

**Additional context**
I've also updated all peak addons except for SEO to the newest version

**Comment by robdekort** [comment]
Hey check this part “ Remove always_show_set_button property from Bard fields”
in https://github.com/studio1902/statamic-peak/blob/main/CHANGELOG.md. That should fix this for you.
