### ISSUE TITLE
Animated gif becomes static?

### ISSUE THREAD

**Issue by Aquive** [studio1902/statamic-peak#321]
**Describe the bug**
When uploading a animated gif into an article the gif becomes static. When I do right mouse and open in new tab so the gif is directly accessed it still is static. So it seems it is a problem when uploading/processing I guess?

**To Reproduce**
1. Create an article
2. Click on + sign in the content and choose image.
3. Take an animated gif and upload it.
4. Check frontend to see the static gif.

**Expected behavior**
An animated gif :)

**Additional context**

Edit: When enable image uploading for the article bard field. So I can upload an image just by draging an image into the editor or just clicking the image icon and inserting the animated gif, it actually does work.

Composer.json
```
    "require": {
        "php": "^8.0",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.14",
        "laravel/tinker": "^2.7",
        "statamic/cms": "3.4.*",
        "studio1902/statamic-peak-browser-appearance": "^1.0",
        "studio1902/statamic-peak-commands": "^1.0",
        "studio1902/statamic-peak-seo": "^1.0",
        "studio1902/statamic-peak-tools": "^2.0"
    },

```

**Comment by Aquive** [comment]
@robdekort Thanks you for your fast reply. I am not sure what this means. When I use Statamic default feature, it does work. See below.

PS: did you see my edit? 

Edit: When enable image uploading for the article bard field. So I can upload an image just by dragging an image into the editor or just clicking the image icon and inserting the animated gif, it actually does work.

**Comment by robdekort** [comment]
Check `images.yaml`. There's a property on the asset container in Peak that uses `source_preset: replacement`. This means all images uploaded to the container will get treated with this:

```
'replacement' => ['w' => 4500, 'fit' => 'max'],
```

As defined in Peak in `assets.php`. This is all native functionality. If you turn off the source preset the gif will stay animated so there should be a better handling of gifs in that part of Statamic.

**Comment by Aquive** [comment]
Thank you, I will check it out!

**Comment by Aquive** [comment]
@robdekort removing the line `source_preset: replacement`  from the `yaml` fixed the issue. I am not sure what the tradeoff is. But I guess I will experience it soon enough :)

Thanks for the great support, it's is very much appriciated :)

**Comment by duncanmcclean** [comment]
Just opened a PR on the Statamic side to fix this: https://github.com/statamic/cms/pull/8512

**Comment by robdekort** [comment]
Oh neat!
