### ISSUE TITLE
Eloquent Support

### ISSUE THREAD

**Issue by MattHadfield113** [studio1902/statamic-peak#322]
**Is your feature request related to a problem? Please describe.**
We use a K8S enviroment to host our websites, and therefore need to use the Eloquent driver.

When trying to import the existing structure, we get the following -

```
Blueprints imported
 35/35 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
Fieldsets imported
 0/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
   Error 

  __clone method called on non-object

  at vendor/statamic/cms/src/Entries/Collection.php:330
    326▕     }
    327▕ 
    328▕     public function fallbackEntryBlueprint()
    329▕     {
  ➜ 330▕         $blueprint = (clone Blueprint::find('default'))
    331▕             ->setHandle(Str::singular($this->handle()))
    332▕             ->setNamespace('collections.'.$this->handle());
    333▕ 
    334▕         $contents = $blueprint->contents();

      +21 vendor frames 
```

**Describe the solution you'd like**
Starter kit to work with the Eloquent Driver.

**Describe alternatives you've considered**
No alternatives.

**Comment by robdekort** [comment]
I'm fairly positive this is not an issue on my side but on the eloquent driver side. You might wanna raise an issue there.
