### ISSUE TITLE
Adding hyperlink to image component?

### ISSUE THREAD

**Issue by Aquive** [studio1902/statamic-peak#324]
**Is your feature request related to a problem? Please describe.**
When managing content for an article, I want to be able to add a hyperlink to an image. It is placed as an image component in the bard field.

**Describe the solution you'd like**
Easy to use feature which makes it possible to add a link to an image.

**Describe alternatives you've considered**
Adding an image, and then editing code manually, but this seems not possible.

**Comment by robdekort** [comment]
Hey Akif. This doesn't have much todo with the kit, but it's native Statamic functionality that's already there. Add a link in Bard and select Asset in the popup to create a link to an asset:
<img width="393" alt="Screenshot 2023-06-20 at 13 02 42" src="https://github.com/studio1902/statamic-peak/assets/69107412/21ea8ce4-61df-4997-ae4c-8d214aa486aa">

If the asset option is not available on your site make sure you select an asset container in this particular bard field config.

**Comment by Aquive** [comment]
Hi @robdekort, thanks for your swift answer as always.

We are using the build in peak component to add images because it has all those build in features for serving optimized sizes and responsiveness etc (see below screenshot). Is it in the current state possible to add a link to it? Or would that be custom work. If so, i'll dive into it and add it myself. But I though this might be a good default feature?

![Dummy-Content-‹-Blogs-‹-Collections-‹-Statamic](https://github.com/studio1902/statamic-peak/assets/197229/64f91732-2b5d-4e41-9b67-8fa2d3ccebbf)

**Comment by robdekort** [comment]
I see. That would be up to you to implement. Pretty easy though. You can simply edit the fieldset and image partial!

**Comment by Aquive** [comment]
Yeah I will do that. Thanks for the suggestions!

As I said, good one for on the feature list. "Nice to have" ;)

**Comment by robdekort** [comment]
🤔 I never had the need to offer that to be honest. I prefer keep the basic as lean as possible. But who knows :-).
