### ISSUE TITLE
Social media - Add services

### ISSUE THREAD

**Issue by mbootsman** [studio1902/statamic-peak#325]
Add Pixelfed and Soundcloud please.

**Comment by marcorieser** [comment]
@robdekort if you agree adding these, I can quickly do that.

**Comment by robdekort** [comment]
Yeah feel free to PR this in @mbootsman. It would however also require a PR to Statamic to get the right icons in there. Closing for now.

**Comment by marcorieser** [comment]
@mbootsman you can vote the FR here:
https://github.com/statamic/ideas/issues/1011
