### ISSUE TITLE
Blade Version of Peak starter kit

### ISSUE THREAD

**Issue by Nicolascanala** [studio1902/statamic-peak#340]
**Is your feature request related to a problem? Please describe.**
I don't enjoy using Antlers, nor does the company I work at, nor does my own business partner. We're always frustrated by it, and feel like it's unnecessary, given that Blade is such a powerful templating language. This means we always end up making Statamic sites with Blade.

**Describe the solution you'd like**
I'd love to have access to Peak written in Blade. I've done this myself a few times, but it's just a lot of work. It'd be great if there's a solution out of the box.

**Describe alternatives you've considered**
I've re-created most of Peak's functionalities in Blade myself. I've made my own personal starter kit that we use for freelance projects, and my company has done this as well. I've often times considered not using a starter kit altogether because of this.

**Comment by robdekort** [comment]
I enjoy using Antlers. I love it and when it clicks it makes a lot of sense. I feel Antlers it's more geared towards frontend developers, where Blade probably appeals more to backend developers. Which is fine.

I can imagine it's a lot of work. But I'm not interested in using Blade, so don't expect anything from me regarding this.

You're welcome to fork it and maintain your own version though.
