### ISSUE TITLE
Cookie alert overlays mobile menu

### ISSUE THREAD

**Issue by Kuldas** [studio1902/statamic-peak#350]
### Bug description

If the cookie banner for embedded videos is turned on in the global settings, the notification that appears overlays the mobile menu.
I already have a PR ready that adds the `isolate` class to the `_video.antlers.html` component. I think this is the ideal solution and avoids the confusion with `z-index`.

![peak-video-component-collapse](https://github.com/studio1902/statamic-peak/assets/15139047/d91c6173-fac7-4f66-b258-53915841dd99)

### How to reproduce

1. Install peak
2. Use `npm run dev`
3. In the control panel activate the cookie banner for embedded videos
4. Use devtool to set up mobile view
5. Open the mobile menu near the embedded video

### Environment

```yaml
Statamic - latest
PHP - 8.1
Laravel - v10
Peak - latest with addons
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

**Comment by robdekort** [comment]
Nice catch!
