### ISSUE TITLE
Precognition forms don't wait on input type validation

### ISSUE THREAD

**Issue by stefankempf** [studio1902/statamic-peak#367]
### Bug description

I have a text field with the input type email, I see the input type rendered in the form `<input type="email"` but when I send the form, the default browser notification for this type validation is not triggering.

![CleanShot 2023-12-11 at 12 04 30](https://github.com/studio1902/statamic-peak/assets/20299885/3c44843d-ed4e-4df9-b52c-6c7e8d60e2d3)

![CleanShot 2023-12-11 at 12 08 16](https://github.com/studio1902/statamic-peak/assets/20299885/99c3cff9-103b-4318-a806-14bb40cf9e61)

### How to reproduce

Create a form, add a text field and set the HTML5 input type to "email"

### Environment

```yaml
Statamic Addons ..................................................................................................................................  
  studio1902/statamic-peak-browser-appearance ................................................................................................ 3.3.3  
  studio1902/statamic-peak-commands .......................................................................................................... 3.1.0  
  studio1902/statamic-peak-seo ............................................................................................................... 7.3.2  
  studio1902/statamic-peak-tools ............................................................................................................. 4.0.5
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by robdekort** [comment]
We don't use the browser validation. You have to setup the validation on the field yourself. This just sets the input type.

**Comment by stefankempf** [comment]
yeah got it, makes sense. might need a break 😄

**Comment by robdekort** [comment]
Haha, enjoy!
