### ISSUE TITLE
Button Component - Can't link to entries in a collection other than the pages collection

### ISSUE THREAD

**Issue by twd3** [studio1902/statamic-peak#375]
### Bug description

I tried to link a buttons entry to a new collection (other than pages) and it doesn't work for some reason. Looked everywhere can't figure it out.

### How to reproduce

Make new collection, mine is system_pages. Make new entry in that new collection. Go to home page entry and add a button with link_type entry. Select entry from that new collection. Save and go to frontend. You will see no href but all other attributes work. If you link to entry in pages collection everything works.

### Environment

```yaml
php 8.2.14
statamic 4.42.0
laravel 10
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by robdekort** [comment]
Does you `system_pages` collection have a route?

**Comment by twd3** [comment]
Ahhhh, oooops. Sorry, that was it. Thank you!

**Comment by robdekort** [comment]
Glad that was it.
