### ISSUE TITLE
When installing in Laragon I get a statamic.com license error

### ISSUE THREAD

**Issue by Sennik** [studio1902/statamic-peak#379]
### Bug description

As a Windows user I use Laragon to develop Laravel Statamic applications. When trying to install Peak on a fresh Laravel installation (Or  as a starter kit through the CLI) I get: 

``` Cannot connect to [statamic.com] to validate license!

### How to reproduce

Install Peak on Laravel within Laragon, On a fresh Laravel or directly through the CLI as a starter kit option.

### Logs

_No response_

### Environment

```yaml
Windows 11 with Laragon
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by marcorieser** [comment]
I believe the statamic.com servers for licensing have problems atm. 
https://github.com/statamic/cms/issues/9359

**Comment by marcorieser** [comment]
@Sennik Can you check again, went trough smoothly here.

**Comment by Sennik** [comment]
Great, it works! Thank you both for the answers and swift solution (Did not expect an issue with the licensing servers because Laravel install went smoothly)

**Comment by robdekort** [comment]
Happy to. Glad it works again. I understood the core CMS itself got an update a while back to prevent issues there. I just informed Jason that this might be an issue in the CLI still. He was happy with that call. So hopefully in the future this won’t happen again.

**Comment by robdekort** [comment]
https://github.com/statamic/cli/issues/67
