### ISSUE TITLE
Upgrading to new release

### ISSUE THREAD

**Issue by zeddyblue** [studio1902/statamic-peak#38]
Hi Rob, 

Loving the peak starter kit and all the effort to make this. 

I was just wondering what procedure you use to upgrade to the latest release of peak, say from v1.10 to v1.12?

**Comment by robdekort** [comment]
There is none to be honest. I just cram every new useful thing in here and today's state is the state of today's new project. While still working on something I might manually update stuff but after that it's on it's own. Until it's not and then there's manual labour involved.
