### ISSUE TITLE
Starter kit config [starter-kit.yaml] does not exist.

### ISSUE THREAD

**Issue by breizhwave** [studio1902/statamic-peak#400]
### Bug description

Starter kit config [starter-kit.yaml] does not exist.

                                                                          
    There was a problem installing Statamic with the chosen starter kit!  

### How to reproduce

installing statamic from scratch with choice of peak as astarter kit

### Logs

```shell
INFO  Application key set successfully.  

> @php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
Collections cleared successfully.
Navigations cleared successfully.
Trees cleared successfully.
Taxonomies cleared successfully.
Assets cleared successfully.
Globals cleared successfully.
Forms cleared successfully.
Users cleared successfully.
User groups cleared successfully.
User roles cleared successfully.
Blueprints cleared successfully.
Fieldsets cleared successfully.
Views cleared successfully.
Statamic configs reset successfully.
Starter kit config [starter-kit.yaml] does not exist.

                                                                          
    There was a problem installing Statamic with the chosen starter kit!
```

### Environment

```yaml
php 8.2
laravel 11
```

**Comment by marcorieser** [comment]
Works fine here. Can you run `composer global update statamic/cli` and try again?

**Comment by breizhwave** [comment]
thks, am on version 3.3.1 and still fails, i updated my github token too ([link](https://github.com/Stillat/the-agency-starter-kit/issues/1))
Statamic CLI Tool 3.3.1

**Comment by marcorieser** [comment]
What is your setup in which you run the command? Does installing a different starter kit work?

**Comment by breizhwave** [comment]
@marcorieser thks, debian infomaniak public cloud, fails on all starter kits.... still investigating..

**Comment by robdekort** [comment]
This issue is not related to Peak. You might wanna open an issue in Statamic Core.
