### ISSUE TITLE
Extending peak:install commands

### ISSUE THREAD

**Issue by seehat** [studio1902/statamic-peak#402]
Hey, thx for this great plugin and starter kit. 

Is it possible to add own custom blocks and presets to the `peak:install:*` commands?

**Comment by marcorieser** [comment]
Not yet afaik but this is something I'd like to PR into it the addon someday.

**Comment by robdekort** [comment]
Hey, glad to hear you like it. 

I’m closing this as it’s a question regarding the commands addon and not an issue with the Peak core kit. Feel free to open a discussion about this on the commands repository with thoughts on what you’d like. It’s not something I have planned for the near future though. 

What you can do today however, is publishing stubs for the existing blocks and presets to make them your own. I also welcome PR’s with presets. Please discuss them first so I don’t have to disappoint you by closing a PR you’ve put time in.

**Comment by seehat** [comment]
Thx, oh sry, I thought I posted it to the addon repo. Alright. Thx!

**Comment by robdekort** [comment]
All good
