### ISSUE TITLE
Search form and template

### ISSUE THREAD

**Issue by robdekort** [studio1902/statamic-peak#45]
Add a basic implementation of Statamic search. Off by default. Easy to include.

**Comment by sigersmit** [comment]
Just saw the video from Jack @ Youtube, but doesn't seems to be that easy? Because you need to add fields you want to be indexed?

**Comment by robdekort** [comment]
Ah thanks, tbh I didn't use search yet in v3. I'll check the vid tonight.

**Comment by robdekort** [comment]
Oh yeah, I'd say add the result template with some sane structuring (maybe fetching a bard search result snippet, or the meta desription), a form that's in a partial but not included in the header by default and adding the replicator fields to the index by default so users see what they can expand upon. What do you think?

**Comment by sigersmit** [comment]
That sounds good. And a reference to the YT video in the your docs.

**Comment by robdekort** [comment]
Oh yeah, great idea! Will do when I get to it.
