### ISSUE TITLE
Favicon generation

### ISSUE THREAD

**Issue by robdekort** [studio1902/statamic-peak#48]
Auto generate favicons. Together with @austriker27.

**Comment by austriker27** [comment]
Let's dooooo it 💪🏻 (as time permits..)

**Comment by robdekort** [comment]
Same same, no rush.

**Comment by vannut** [comment]
Great addition! Fill me in.... where do we define the icon-source? and should it generate the corresponding files from the source?

**Comment by robdekort** [comment]
This is all David's idea. He made a pretty grand start a while back. 

https://twitter.com/austriker27/status/1321907064122138624?s=21

I've yet to figure out how we can generate all needed types but this will be fun!

**Comment by robdekort** [comment]
I came across an article recently that stated we don't need as much versions as realfavicongenerator generates these days. That would make stuff easier. And since Peak (and me) doesn't support IE11 but just the two recent versions anyway. I'll look it up.

**Comment by robdekort** [comment]
https://medium.com/swlh/are-you-using-svg-favicons-yet-a-guide-for-modern-browsers-836a6aace3df

This article. Together with what RFG generates we should be able to figure out an ideal set right?

It would be great if we could generate PNG's from an SVG with a backdrop color on the fly somehow. I don't think Glide does this.

**Comment by sjclark** [comment]
To be honest these days I literally JUST do an SVG favicon. Figure that covers every base that I care about. But the more the merrier!

**Comment by robdekort** [comment]
No touch icons? So lazy. We'll fix it for you.

**Comment by robdekort** [comment]
Does anyone know if ImageMagick is installed by default with Forge?

Would that be an acceptable installation requirement?

**Comment by philipboomy** [comment]
New servers yes. Saw a tweet a few weeks ago from James stating that.

**Comment by robdekort** [comment]
Thanks! Good to know.

**Comment by robdekort** [comment]
Any thoughts folks? It seems this is the minimum we need for all modern browsers and to pass Lighthouse. We shouldn't have to care about a .ico cuz we don't support older browsers anyway.

SVG of any size, main icon:
`<link rel="icon" href="favicon.svg">`

Single color Safari icon, on transparent bg
`<link rel=”mask-icon” href=”mask-icon.svg” color=”#000000">`

iOS touch icons. 180x180
`<link rel="apple-touch-icon" href="apple-touch-icon.png">`

manifest.json for lighthouse one 512x512 png icon
```
{
    "icons": [
        { "src": "/512.png", "type": "image/png", "sizes": "512x512" }
    ]
} 
```

What do you think @austriker27.

**Comment by robdekort** [comment]
I don't see how we can generate this from one image though. The main SVG should be able to have to have multiple colors. The Safari icon needs to be single color and you can go as wild as you want with the PNG's / touch icons.

The manifest we should be able to generate with a custom route.

But that would mean you would need to upload 3 icon files? Two svg's, one PNG?

**Comment by robdekort** [comment]
What could work, I don't know how yet, is uploading one SVG logo (multicoloured), picking a theme color and a background color. From that we should generate:

1. The regular `favicon.svg` (the svg as is).
2. A `mask-icon.svg` where every fill/stroke get's the selected theme color by using the color attribute (I hope). 
3. A `apple-touch-icon.png` where the logo is rendered on a coloured background (another color setting). I think we need `imagick` for this which I don't like as a requirement.
