### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by robdekort** [studio1902/statamic-peak#50]
A demo video so users get a clear picture what Peak is and does..

My issues with it: I don't like making them and it will be outdated within weeks. 

Any ideas?

**Comment by janparkio** [comment]
Show how the Page builder, modular fieldset, and single-collection works and the SEO features (for the video).
For me, that and the overall tailwind config files are the biggest wins (perhaps some images are enough).

It has been pretty easy for me to create my own "templates" following the logic.

**Comment by robdekort** [comment]
Thanks Jan. Appreciate the feedback! Maybe come Christmas I get the 'spirit'.

**Comment by sigersmit** [comment]
Would really like to see a short demo / walkthrough video! It's gonna be a cold Christmas, so no need to go outside ;-)

**Comment by robdekort** [comment]
Thanks for letting me know folks. I'll see what I can do. At least it won't be for nothing. That's nice.

**Comment by sytheveenje** [comment]
Maybe you could make multiple videos with a small subject per video. You could record it as one video, but cut them in smaller clips and upload them. That way, when a small part gets outdated, re-recording is not so much of a deal. 

Jack & Adam cover recording in an in depth podcast:
https://fullstackradio.com/150

**Comment by robdekort** [comment]
Great idea! I heard that podcast, def. not gonna spend money on a mic but the other tips were very very nice!

**Comment by sytheveenje** [comment]
Make the screencast for sponsors only like Caleb does and then buy a mic from that money!

**Comment by robdekort** [comment]
Ha! But I don't want a mic :-)

**Comment by mnlmaier** [comment]
maybe some extended docs would also help (and be easier to maintain?)

**Comment by robdekort** [comment]
Yes, thinking of that... but but but: more work ;-)

**Comment by robdekort** [comment]
Improved the README tonight with some inline screenshots. One day we might get docs. Closing this issue for now as I don't see myself recording anything soon.

**Comment by sjclark** [comment]
Good point @robdekort - would probably make more sense for it to be a **voice-activated 3D Virtual Reality tour** of the features, I reckon we could get Vin Diesel to do the voiceovers?

**Comment by robdekort** [comment]
Ok REOPENING NOW!

**Comment by sjclark** [comment]
Just got in touch with his agent, apparently he's booked through until 2024. Also turns out voice-activated 3D VR is really expensive. Maybe close this issue, and we'll think about photographing some diagrams on a whiteboard instead? 🤷‍♂️

**Comment by robdekort** [comment]
Yeah ok... 😥
