### ISSUE TITLE
Add more image size - including base64

### ISSUE THREAD

**Issue by janparkio** [studio1902/statamic-peak#51]
**Is your feature request related to a problem? Please describe.**
So I am building a hero section and my monitor is 27 inches. I find myself seen a lot of pixels on the images since the _picture.antlers.html has a cool feature to make images responsive. I tried to modify the largest image size, however, I don't see any difference from 1680w to 3000w. So what am I doing wrong?
![Screen Shot 2020-12-16 at 16 52 28](https://user-images.githubusercontent.com/9617583/102399534-85248a80-3fbf-11eb-98f7-635fb027e444.png)

**Describe the solution you'd like**
I would like to understand the logic of how these sizes are being created and add more. Even a base64 feature, which I've seen in other pages or tools like GatsbyJS with their gatsby-image plugin. Makes a temporary image on the first load.

**Describe alternatives you've considered**
Increased the biggest image. But it doesn't seem to work.

**Additional context**
I am using the partial '_picture.antlers.html' in all my images.

**Comment by robdekort** [comment]
Hey Jan! That's not how responsive images work. Please read [this section](https://github.com/studio1902/statamic-peak#assets) of the readme and follow the link to one of my blog posts explaining a bit more how the partial (and responsive images) work.

What you def. want to do in your case is add a preset to `config/statamic/assets.php`. See line 69 for all the presets we currently use in the picture partial. You can as much there for your site as you want and update the picture partial to use your preset! 

Hope it helps!

**Comment by janparkio** [comment]
Thank you! I do understand now (a bit more) how it works.

**Comment by robdekort** [comment]
Awesome, feel free to let me know if you have any other q's.
