### ISSUE TITLE
Prose class on both article tag and text set component

### ISSUE THREAD

**Issue by twd3** [studio1902/statamic-peak#55]
**Describe the bug**
I am going over how you used the Tailwind typography plugin to style bard. I see you have the "prose" class on both the article container for the bard as well as the text set partial the bard uses. Isn't it true that you wouldn't need the prose class on the text set partial because it's already on the article tag that the text lives in?

**To Reproduce**
1. Go look at resources/views/page_builder/_article.antlers.html and see prose
2. Go look at resources/views/components/_text.antlers.html and see prose
3. Does the prose class on the text component need to be there and if so why?

**Additional context**
It could be there for a reason and I just don't know why because I'm new to the typo plugin...

**Comment by twd3** [comment]
Shoot, I think I was looking at an old version of the kit. When I look at current repo the article tag doesn't have the prose class sorry.

**Comment by robdekort** [comment]
Ah yeah, I changed that a while back so the prose styles won’t override the styles in bard sets, like figure or quote.
