### ISSUE TITLE
Other hydration of CSRF token approach

### ISSUE THREAD

**Issue by vannut** [studio1902/statamic-peak#62]
When we want to use the full force of caching for our pages with forms etc, we need a way to hydrate the CSRF token to protect our request endpoints against Cross Site Request Forgery. 

At the moment we use a `{{ dynamic_token }}`-tag which [periodically hydrates](https://github.com/studio1902/statamic-peak/blob/main/app/Tags/DynamicToken.php#L49) the csrf-input field (atm on load and every 15 minutes). 

Basically it _just_ makes an Ajax request to a [specific endpoint](new FormData(this.$refs.form)})) to retrieve the new, current [csrf-token given by laravel](new FormData(this.$refs.form)})). 

I was wondering if there were any downsides to put this hydration _into_ the form sent request itself. Right before we make the actual  [request to the form-endpoint](https://github.com/studio1902/statamic-peak/blob/main/resources/views/page_builder/_form.antlers.html#L63).

In pseudo code:
```javascript
sendform() {
  this.sending = true;
  fetch('/!/DynamicToken/refresh') 
    .then((body) => {
      return body.text();
    })
    .then((newToken) => {
      let data = new FormData(this.$refs.form)});
      data._token = newToken;

      // do the actual request with the new token
    })
},
```
We then are able to discard the whole `dynamic_token`-tag & don't have to make any additional calls every x-minutes.

Or am I missing any pittfalls?

**Comment by robdekort** [comment]
I'm just a frontender and not 100% sure but I think you might be right. It's been a while since I mangled with that stuff. Have you tried this?

**Comment by vannut** [comment]
> Have you tried this?

Yes! Currently only on my local environment. Only with a slightly different approach, I wrote wrapper which bundles this behaviour for inco a simple `apiCall(url, data)` function.

But the idea is the same. When run, it fetches the csrf token; and then uses it to make a subsequent fetch call to my endpoint:

```javascript
export async function apiCall(endpoint = '', data = {}) {

  const url = '/!/astatamic-vloot-addon/api'+endpoint;

  // token inladen..
  return updateCsrfToken()
    .then( async (csrfToken) => {
      data._token = csrfToken;

      // making the request
      const fetchResult = await fetch(url, {
        ...
      })
    
      // do things (result + error)

    })
  }

async function updateCsrfToken() {
  return await fetch('/!/DynamicToken/refresh', {
    method: 'GET',         
  }).then((body) => {
    return body.text();
  })
}
```

**Comment by robdekort** [comment]
You probably know what I'm gonna ask you for now right?

**Comment by vannut** [comment]
Haha. Yeah: PR? 

But First wanted to see if I was missing something 😀

**Comment by robdekort** [comment]
Yup yup. Haha. I don't think so but I have to be honest this stuff ain't fresh. I'll be happy to test it thoroughly when the time comes.

**Comment by jelleroorda** [comment]
Well functionality-wise there would not be any disadvantages (since in both cases it submits the form). However, you would have to wait for the first request to finish before it can send the form. I think in the optimal scenario it would do the request:
1. On pageload, since in the first 15 minutes chances are biggest someone will submit the form
2. If the 15 minutes have expired, then fall back to the method you’re suggesting.

Not sure if that would be possible, but at least it would prevent pages left open to spam your server.

In reality I would probably pick the current method since I want my forms to be snappy (or at least not slower than they have to be).

**Comment by robdekort** [comment]
I don't think my opinion matters much. Haha. I'm mostly glad I got this working at the time as it's not really my cup of tea. 

So folks. What do we do?

**Comment by vannut** [comment]
Maybe we should leave it like it is for simplicity sake. 
In the end the result is the same, wether you refresh the token on pageload + every 15 minutes; or just before sending the form.

The latter method indeed invokes an additional roundtrip for getting the fresh token right before the submit of a form. With the downsides @jelleroorda mentions. So lets just keep the functionality as-is.
