### ISSUE TITLE
Social card height: 600 or 630

### ISSUE THREAD

**Issue by vannut** [studio1902/statamic-peak#63]
We have some mixed signals in the social card configuration. 
In the fieldset we have the following instruction:

```The recommended size is 1200px x 630px```

While in [snippets/_seo.antlers.html](https://github.com/studio1902/statamic-peak/blob/main/resources/views/snippets/_seo.antlers.html#L108) we have a glide tag with the dimension 1200x**600**px

Happy to make a PR, but which of the dimensions is correct?

**Comment by robdekort** [comment]
You're right, should be 630. Cool if you wanna PR that in, beware the meta on line 110 also has the incorrect dimensions it seems.

**Comment by vannut** [comment]
Done in #64
