### ISSUE TITLE
Package to install into existing Laravel app

### ISSUE THREAD

**Issue by jobverplanke** [studio1902/statamic-peak#67]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Not applicable

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

I was wondering if Studio1902 would be interested if there was a package of this preset for Statamic instead of an app install or maybe both?
If so, I would like to help by submitting a PR or consider other possibilities to make this happen.

What are your thoughts on this?

**Comment by robdekort** [comment]
Hey Job, thanks for your message. I'm not really sure what you mean. However feel free to reach out, you can mail me as well if you want: rob@studio1902.nl.

**Comment by jobverplanke** [comment]
I've send you an email :)

**Comment by robdekort** [comment]
Cool, I'm all for it. Tell me what I must do.

**Comment by jobverplanke** [comment]
I'm gonna close this issue as the feature came to life in a new repository.
For people who are looking for a option to use Peak in a existing Laravel/Statamic application look at the following repository: https://github.com/studio1902/statamic-peak-package

**Comment by robdekort** [comment]
Fantastic work Job! I love it. Thanks.
