### ISSUE TITLE
Asset Container Error

### ISSUE THREAD

**Issue by kerns** [studio1902/statamic-peak#71]
I installed peak together with Statamic via the cli, but encounter this error when viewing any page in the cp. Could easily be an issue with my local config but I've tried to follow the docs step for step.

<img width="1179" alt="Screen Shot 2021-02-06 at 13 29 23" src="https://user-images.githubusercontent.com/20254/107118794-57ebae80-6883-11eb-8a69-b2dfa9479dc3.png">

**Comment by robdekort** [comment]
Hi thanks I see. I added an asset container in yesterdays update and I think there's still an asset field in the default fieldsets without a specified container. I'll investigate and update asap.

**Comment by robdekort** [comment]
Found it, updated release incoming! Thanks for reporting!
