### ISSUE TITLE
Edit Link

### ISSUE THREAD

**Issue by kerns** [studio1902/statamic-peak#74]
One of the things I have in my Craft CMS default is an "Edit" link that opens the current page for editing in the control panel.

If you are logged in have the correct privileges it's a very useful snippet to have in almost any default setup. There are a number of ways to integrate something like this such that it doesn't interfere with the layout.

**Comment by robdekort** [comment]
Ah ok. Like an admin button you mean? Maybe something together with the TW breakpoint pill?

Verstuurd vanaf mijn iPhone

**Comment by robdekort** [comment]
You'd have to manually create the backend URL. That does feel a bit hacky. Curious if you have any thoughts!

**Comment by vannut** [comment]
Actually the page-entry has an `edit_url`:
![Schermafbeelding 2021-02-07 om 22 14 20](https://user-images.githubusercontent.com/7419859/107159703-041bbb00-6992-11eb-9a5f-bf97bfe9598f.png)

And there is also an `logged_in` / `logged_out` so it could be as simple as:
```
{{ if logged_in }}
  <aside class="absolute top-0 left-0">
      <a href='{{ edit_url }}'>edit</a>
  </aside>
{{ /if }}
```
Somewhere in a partial :)

**Comment by robdekort** [comment]
Oh Wow, there's an `edit_url`. Great. That really makes it easy. I didn't know that. 
I was thinking we could add it in the footer? Or would that be less helpful due to the possible scrolling?

**Comment by kerns** [comment]
Nice. Yep. I only dabble with Statamic but also felt certain there would be a url.

RE: integration @robdekort, there are so many ways to skin this cat. I personally tackle it with a designated "hit zone" which triggers opacity on hover.

https://user-images.githubusercontent.com/20254/107209898-b8095e80-6a03-11eb-9010-fb6b1f902db0.mov

But it could also be integrated alongside the breakpoint utility. I think ultimately both of these should not be fixed layers of a static UI that are always visible due to the potential for conflict with the things going on underneath.

**Comment by robdekort** [comment]
I like that idea and I agree with your reasoning. I'll try and fix it for the TW notification as well as the to be added edit link.

**Comment by kerns** [comment]
Here is one take on it (hover top right)

https://play.tailwindcss.com/h6x7cnOapT

You can toggle visibility with a cookie. Solution may need tweaking for mobile. I didn't focus too much on semantic structure bc of time.

**Comment by robdekort** [comment]
That's fantastic. I don't really think this even has to be a thing on mobile tbh.

**Comment by kerns** [comment]
Cool. You're right, more for touch devices more broadly, ...regardless, I think it would still work, just becoming visible after a tap.

**Comment by robdekort** [comment]
True! I'm implementing it atm. Hope to release soon.

**Comment by kerns** [comment]
This one is also fun. TW just makes it too easy. https://play.tailwindcss.com/ipV42iZQJV

**Comment by robdekort** [comment]
It's live now!

**Comment by kerns** [comment]
Is there a smart way to update a Peak deployment where the deployment is just a playground of no importance? But still keeping dummy assets, content etc.?

**Comment by robdekort** [comment]
You could add it as a remote and then manually merge changed files in. There's no really easy or magic way unfortunately.
