### ISSUE TITLE
Disable Search Button When Input is Empty

### ISSUE THREAD

**Issue by kerns** [studio1902/statamic-peak#77]
I know this is probably outside the scope of what you want to be providing with Peak, but since you _are_ including a search field... :)

The issue is that due to the specific pattern invoked users can also interpret the search icon as a button for closing the input field, which is modal. It is also placed directly under the cursor when opened, so accidental input and absorbing clicks is also a risk.

The solution is for empty search submissions to be disabled... not allowed, until users enter text. Then if they click a second time the input would be closed instead of submitting an empty search.

**Comment by robdekort** [comment]
No it's valid! We should set best practices right. Will be fixed in an upcoming update. Luckily it's very easy with Alpine.
