### ISSUE TITLE
Tailwind CSS Jit Compiler

### ISSUE THREAD

**Issue by robertguss** [studio1902/statamic-peak#87]
Would you like me to submit a PR that adds the new Tailwind CSS Jit compiler to Peak? 

https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css

I already have a working version.

**Comment by robdekort** [comment]
Hey Robert. Thanks so much. I have it running as well but I feel it's a little early to merge in atm. I ran into some issues with custom variants not working on this one project. What do you think?

**Comment by robdekort** [comment]
Feel free to ping me on discord if you want to discuss this. I'd love to have it in asap.

**Comment by robertguss** [comment]
If you are having issues, I would wait. It might make the most sense to pull it in once it is included in the main tailwind package which is v3 I believe.

You did a great job with this starter kit btw. I was going to make my own but then I found this and was pleasantly surprised. If you ever need some help with this project, just ping me and I will do what I can.

**Comment by robdekort** [comment]
That's awesome, really appreciate that. Let's wait a little then. I'm not afraid to put pre-release stuff in there if it's stable enough. The time saved is so awesome with the JIT compiler.

Feel free to join the Discord. I bounced around some ideas for a Peak v2 and I'd love some input on it. 

Thanks!
