### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by klickreflex** [studio1902/statamic-peak#88]
To gain a better understanding of Peak's features I just manually added all its features into an existing Statamic site and stumbled over two things in [Configuration Changes](https://peak.studio1902.nl/other/configuration-changes.html):

- the command to warm the caches is mentioned to be  added to `routes/console.php` yet it's to be found in  `app/Console/Commands/WarmCommand.php` 
- It would have helped me if the assets container `favicons` was documented here (only other way to find this through documentation is implicitly within the favicon section, which mentions you need to delete said container if you don't want to use the feature at all)

**Comment by robdekort** [comment]
Great feedback, thanks a lot! I just pushed some updates to the docs. Know that you can add issues for the docs there on the docs repo: https://github.com/studio1902/statamic-peak-docs/issues. Keep 'm coming!
