### ISSUE TITLE
Include current locale in alternate hreflang elements

### ISSUE THREAD

**Issue by vannut** [studio1902/statamic-peak#90]
At the moment we _exclude_ the current lang being displayed in the head:

```html
{{ locales }}
    {{ unless locale.key == current }}
        <link rel="alternate" hreflang="{{ locale:full replace="_|-" }}" href="{{ permalink }}">
    {{ /unless}}
{{ /locales }}
```

I recently ran ahrefs site explorer but got this error:

> Self-reference hreflang annotation missing
> Issue details
>To indicate multiple language/location versions of a page to the search engines, each language version of a page must list itself as well as all other language versions.
> Hreflang annotations without the self-referencing link may be ignored or misinterpreted by the search engines.
> 
> How to fix
>
> Review all the pages with missing self-referencing hreflang annotations listed in this report. You can see all hreflang links specified for a given page in the table.
> 
> Make the necessary changes, so that each of these pages has a self-referencing hreflang annotation.
> For example, a Spanish version of your page must have rel="alternate" hreflang="es" annotation with a link to itself.

So if I'm reading this correctly we should also include the current page in the hreflang elements.

**Comment by robdekort** [comment]
Hey didn't we already change this a while back? This looks so familiar.

**Comment by robdekort** [comment]
```
{{# hreflang tags #}}
{{ locales }}
    <link rel="alternate" hreflang="{{ locale:full replace="_|-" }}" href="{{ permalink }}">
{{ /locales }}
```

This should be it then right?

**Comment by vannut** [comment]
It's still in the current [_seo.antlers.html](https://github.com/studio1902/statamic-peak/blob/main/resources/views/snippets/_seo.antlers.html#L31)

But If I read the 'fix' correct we should indeed loose the `unless`.

**Comment by robdekort** [comment]
It indeed is. I'm not sure why as I remember approving someone's PR a while back. I think it was yours. Oh well. I'll change it right a way and tag a release.

**Comment by vannut** [comment]
I can't remember if it was mine :)  
#84  is the only recent localization PR lately from me.

**Comment by robdekort** [comment]
Hmm, odd. Probably a miss merge somewhere. Def. not intentional :-)
