### ISSUE TITLE
Link Blocks broken. Can't save

### ISSUE THREAD

**Issue by zeddyblue** [studio1902/statamic-peak#91]
**Describe the bug**
When I try to create a link block, that is, save and publish it, I get the error "The given data was invalid". An extra block seem to be created without any data when you look at the live preview of the page. 

**To Reproduce**
1. Go to 'page builder'
2. Click on 'Add Link block'
3. Populate all fields for a new link block
4. Try to save and publish
5. See error "The given data was invalid"

**Expected behavior**
Page should save. This used to work on an older version of peak. 

**Screenshots**

![gscreenshot_2021-04-06-141236](https://user-images.githubusercontent.com/811353/113658668-cc0bcc80-96e3-11eb-9fad-ed58e0cfec13.png)

When you go to live preview in this example, I have created two link blocks, You can see the two link blocks, but there is a third block (the first one on the left), with no populated fields. Probably reason for the error, but all fields have been filled. I couldn't work out where in your code this is coming from 

**Desktop (please complete the following information):**
 - OS: Xubuntu
 chrome and firefox

**Additional context**
This works fine on an old version of peak, but I don't know what version. Happy to dig this information down if it helps.

**Comment by robdekort** [comment]
I just noticed this yesterday. I'm very positive it's due to validation not working as expected in Statamic and something must've changed in a recent update. If you remove the `validate: required` from the fields it will save, but you might want to add some conditions to the templates. I'll push out an update soon. Thanks!
