### ISSUE TITLE
Using multisite command creates Error

### ISSUE THREAD

**Issue by snkBarryKrein** [studio1902/statamic-peak#92]
**Describe the bug**
Doing the multisite setup from CLI will run into an error

**To Reproduce**
1. checkout peak
2. cp .env.example .env
2. php artisan key:generate
3. php please multisite

**Expected behavior**
No error occurs

**Screenshots**
``` 
The current site handle is [default], content will be moved into folders with this name. Is this okay? (yes/no) [no]:
 > yes

 Handle of the second site [two]:
 > 

Clearing Stache...
[✓] Stache cleared.

Converting...
[✓] Collection [pages] updated.
[✓] Global [configuration] updated.

   Error 

  Call to a member function in() on null

  at app/Listeners/GenerateFavicons.php:31
     27▕      * @return void
     28▕      */
     29▕     public function handle(GlobalSetSaved $event)
     30▕     {
  ➜  31▕         if ($event->globals->handle() !== 'favicons' || !GlobalSet::findByHandle('favicons')->in('default')->get('use')) {
     32▕             return;
     33▕         }
     34▕ 
     35▕         $svg = GlobalSet::findByHandle('favicons')->in('default')->get('svg');

      +43 vendor frames 
  44  please:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Additional context**
Run in an Ubuntu 20.10, PHP 7.4

**Comment by robdekort** [comment]
Thanks for reporting this. I'm gonna try to dive into this tomorrow.

**Comment by robdekort** [comment]
To be honest I don't have a clue why this happens. I can understand that you need to change `default` in the `GenerateFavicons.php` listener if you change your sites name in `sites.php` but why this fails and how the listener is even relevant. I don't know.

I was able to comment the listener, run the command, add it back and I had a multisite. But then the globals page in the CP greeted me with and error.

I've asked on Discord, but so far no response.

Did you get any further? Maybe you have a clue?

**Comment by robdekort** [comment]
Hahaha that's me. I'm mostly designer and frontender so whenever I write php and it works I move on. 

But luckily bright people can PR it. 😂

**Comment by vannut** [comment]
Without testing itself it looks like the Globalset::findByHandle('favicons') returns null instead of the set. 

So you could add a check for that in the listener and bail early...

**Comment by robdekort** [comment]
Yeah I also noticed I request globals from the `default` site. Which could also be called `en` or `be` or whatever. Not fool proof either.

**Comment by snkBarryKrein** [comment]
The mergerequest fixes this Issue. Thanks @jelleroorda for the contribution!
