### ISSUE TITLE
github oauth token issue, only with Peak

### ISSUE THREAD

**Issue by jasonday** [studio1902/statamic-peak#94]
**Describe the bug**
```
In BaseIO.php line 104:

  Your github oauth token for github.com contains invalid characters: "<TOKEN>"
```
Installing Statamic and choosing "Peak" as the starter, I get this error every attempted install.

**Comment by robdekort** [comment]
Weird. I can install just fine, but once had to add a valid token. Can you maybe add this issue to the Statamic CLI repo? I'm not sure what I could do about this.

**Comment by robdekort** [comment]
Feel free to reopen if it's something I can/should change.
